#!/usr/bin/env python3

import subprocess
import sys
import os

SCRIPT = '/home/siikamiika/.local/bin/interpolate-sub-sync.py'

video_filename = sys.argv[1]
base, ext = os.path.splitext(video_filename)

if sys.argv[2] == 'reload':
    subprocess.call([
        SCRIPT,
        base + '.subsync.jsonl',
        base + '.subsync.srt',
        'normal',
    ])
    sys.exit(0)

time = sys.argv[2]
offset = sys.argv[3]

subprocess.call([
    SCRIPT,
    base + '.subsync.jsonl',
    base + '.subsync.srt',
    'shift',
    time,
    offset,
])
