#!/usr/bin/bash

case $BLOCK_BUTTON in
    1) ibus-setup ;;
    3) ibus restart ;;
esac

if [ "$(ibus engine)" = "uniemoji" ]; then
    echo 😂
else
    echo $(setxkbmap -query | grep layout | awk '{print substr($2,0,2)}')
fi
