#!/usr/bin/env python2

import ibus
import dbus
from subprocess import call, check_output
from os.path import expanduser
import sys

def set_layout(layout):
    call(['setxkbmap', layout])
    call(['xmodmap', expanduser('~/.Xmodmap')])

def set_engine(engine, layout='autism'):
    call(['ibus', 'engine', engine])
    set_layout(layout)

def set_input_mode(mode):
    bus = ibus.Bus()
    conn = bus.get_dbusconn().get_object(ibus.common.IBUS_SERVICE_IBUS, bus.current_input_contxt())
    ic = dbus.Interface(conn, dbus_interface=ibus.common.IBUS_IFACE_INPUT_CONTEXT)
    ic.PropertyActivate('InputMode.' + mode, ibus.PROP_STATE_CHECKED)

def main():
    # Alt+Shift+1: English/Finnish
    if sys.argv[1] == 'autism':
        set_engine('mozc-jp')
        set_input_mode('Direct')
    # Alt+Shift+2: Japanese
    elif sys.argv[1] == 'japanese':
        set_engine('mozc-jp')
        set_input_mode('Hiragana')
    # Alt+Shift+3: Russian
    elif sys.argv[1] == 'russian':
        set_engine('mozc-jp', 'ru(phonetic)')
        set_input_mode('Direct')
    # Super+period: emoji
    elif sys.argv[1] == 'emoji':
        current_engine = check_output(['ibus', 'engine']).strip()
        if current_engine != 'uniemoji':
            set_engine('uniemoji')
        else:
            set_engine('mozc-jp')

if __name__ == '__main__':
    main()
