#!/usr/bin/env python3
import socketserver
from os.path import expanduser
from io import StringIO
import pyperclip
from pymouse.x11 import display_manager
from pymouse import PyMouse
from Xlib.display import Display
from Xlib import X
from Xlib.ext.xtest import fake_input

def unescape_newlines_and_spaces(text):
    result = StringIO()
    text_iter = iter(text)
    for char in text_iter:
        if char != '\\':
            result.write(char)
        else:
            try:
                char = next(text_iter)
            except StopIteration:
                break
            if char == '\\':
                result.write('\\')
            elif char == 'n':
                result.write('\n')
            elif char == 's':
                result.write(' ')
            else:
                result.write('\\' + char)

    return result.getvalue()


class InputServerHandler(socketserver.StreamRequestHandler):

    LINE_MAX_LENGTH = 2 * 1024 ** 2

    def handle(self):
        #print(self.client_address[0])
        client_auth = self.rfile.readline(self.LINE_MAX_LENGTH).strip()
        if client_auth != self.server.auth:
            #print('invalid auth: {}'.format(auth))
            return
        while True:
            self.data = self.rfile.readline(self.LINE_MAX_LENGTH).decode('utf-8').strip().split(' ')
            #print(' '.join(self.data))
            if self.data[0] == 'quit':
                break
            elif self.data[0] == 'mouse':
                self.handle_mouse()
            elif self.data[0] == 'keydown':
                self.server.input.key_press(int(self.data[1]))
            elif self.data[0] == 'keyup':
                self.server.input.key_release(int(self.data[1]))
            elif self.data[0] == 'clipboard':
                self.handle_clipboard()

    def handle_mouse(self):
        x, y = map(int, self.data[1].split(','))
        if abs(x) + abs(y) > 0:
            self.server.input.mouse_move_relative(x, y)
        if len(self.data) < 3:
            return
        mouse_buttons = self.data[2].split(',')
        for mouse_button in mouse_buttons:
            if mouse_button == 'left_down':
                self.server.input.button_press(1)
            elif mouse_button == 'left_up':
                self.server.input.button_release(1)
            elif mouse_button == 'right_down':
                self.server.input.button_press(3)
            elif mouse_button == 'right_up':
                self.server.input.button_release(3)
            elif mouse_button == 'middle_down':
                self.server.input.button_press(2)
            elif mouse_button == 'middle_up':
                self.server.input.button_release(2)
            elif mouse_button == 'xbutton1_down':
                self.server.input.button_press(8)
            elif mouse_button == 'xbutton1_up':
                self.server.input.button_release(8)
            elif mouse_button == 'xbutton2_down':
                self.server.input.button_press(9)
            elif mouse_button == 'xbutton2_up':
                self.server.input.button_release(9)
            elif mouse_button == 'wheel_up':
                self.server.input.button_press(4)
                self.server.input.button_release(4)
            elif mouse_button == 'wheel_down':
                self.server.input.button_press(5)
                self.server.input.button_release(5)

    def handle_clipboard(self):
        if len(self.data) < 2:
            return
        text = unescape_newlines_and_spaces(self.data[1])
        pyperclip.copy(text)
        pyperclip.copy(text, primary=True)


class InputServer(socketserver.ThreadingMixIn, socketserver.TCPServer):

    allow_reuse_address = True

    def __init__(self, *args, **kwargs):
        self.input = kwargs.pop('input')
        self.auth = kwargs.pop('auth')
        super(InputServer, self).__init__(*args, **kwargs)


class XorgInput(object):

    def __init__(self):
        self.display = Display(None)
        self.mouse = PyMouse()

    def key_press(self, code):
        with display_manager(self.display) as d:
            fake_input(d, X.KeyPress, code)

    def key_release(self, code):
        with display_manager(self.display) as d:
            fake_input(d, X.KeyRelease, code)

    def mouse_move_relative(self, x, y):
        pos = self.mouse.position()
        self.mouse.move(*map(sum, zip(pos, (x, y))))

    def button_press(self, code):
        with display_manager(self.display) as d:
            fake_input(d, X.ButtonPress, code)

    def button_release(self, code):
        with display_manager(self.display) as d:
            fake_input(d, X.ButtonRelease, code)


def main():
    xorg_input = XorgInput()
    with open(expanduser('~/.windows-hotkey-server'), 'rb') as f:
        auth = f.read().strip()
    input_server = InputServer(('127.0.0.1', 9888), InputServerHandler, input=xorg_input, auth=auth)
    input_server.serve_forever()

if __name__ == '__main__':
    main()
